export const tableData = [
	{
		id: "1",
		user: "أحمد محمود",
		phoneNumber: "0123456789",
		ticketNo: "C-101",
		ticketPrice: "$40",
		cinams: [
			"سينما مصر",
			"مول العرب",
			"برج الأطنان",
			"سرايا القبة",
			"صيدناوي مول",
			"برج العرب",
		],
		numberOfpeople: 1,
		numberOfBought: "مرة واحدة",
	},

	{
		id: "2",
		user: "محمد الغريب",
		phoneNumber: "0123456789",
		ticketNo: "C-102",
		ticketPrice: "$30",
		cinams: ["سينما مصر", "مول العرب", "برج الأطنان", "سرايا القبة"],
		numberOfpeople: 1,
		numberOfBought: "مرة واحدة",
	},

	{
		id: "3",
		user: "محمد محروس",
		phoneNumber: "0123456789",
		ticketNo: "C-102",
		ticketPrice: "$45",
		cinams: ["سينما مصر", "مول العرب", "برج الأطنان", "سرايا القبة"],
		numberOfpeople: 1,
		numberOfBought: "مرة واحدة",
	},
	{
		id: "4",
		user: "محمد الشيخ",
		phoneNumber: "0123456789",
		ticketNo: "C-103",
		ticketPrice: "$54",
		cinams: ["سينما مصر", "مول العرب", "برج الأطنان", "سرايا القبة"],
		numberOfpeople: 1,
		numberOfBought: "مرة واحدة",
	},
];
